# Generated by Django 4.0.1 on 2022-01-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=70, unique=True)),
                ('day', models.CharField(choices=[('shanbe', 'شنبه'), ('shanbe_1', 'شبنه 1'), ('shanbe_2', 'شبنه 2'), ('shanbe_3', 'شبنه 3'), ('shanbe_4', 'شبنه 4'), ('shanbe_5', 'شبنه 5'), ('shanbe_6', 'شبنه 6')], max_length=8, null=True)),
                ('date', models.DateField(null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('logo_link', models.URLField()),
                ('logo', models.ImageField(default='images\\logo.png', upload_to='images')),
                ('stream', models.CharField(choices=[('vid', 'Video'), ('aud', 'Audio'), ('v_a', 'Video Audio')], default='vid', max_length=3)),
                ('voice_link', models.URLField(blank=True, default='')),
                ('stat_voice_link', models.URLField(blank=True, default='')),
                ('stat_voice_type', models.CharField(blank=True, choices=[('shoutcast', 'Shoutcast'), ('wowza', 'Wowza')], max_length=20)),
                ('video_link', models.URLField(blank=True, default='')),
                ('stat_video_link', models.URLField(blank=True, default='')),
                ('stat_video_type', models.CharField(blank=True, choices=[('shoutcast', 'Shoutcast'), ('wowza', 'Wowza')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
