# Generated by Django 3.2.11 on 2022-01-30 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DateType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_type', models.CharField(choices=[('weekly', 'هفتگی'), ('occasional', 'مناسبتی')], max_length=10, verbose_name='نوع')),
                ('day', models.CharField(blank=True, choices=[('shanbe', 'شنبه'), ('shanbe_1', 'شبنه 1'), ('shanbe_2', 'شبنه 2'), ('shanbe_3', 'شبنه 3'), ('shanbe_4', 'شبنه 4'), ('shanbe_5', 'شبنه 5'), ('jome', 'جمعه')], max_length=8, null=True, verbose_name='هفتگی')),
                ('specified_date', models.DateField(blank=True, null=True, verbose_name='مناسبتی')),
            ],
        ),
        migrations.CreateModel(
            name='VideoStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_stat_link', models.URLField(blank=True, null=True, verbose_name='Stat Link')),
                ('video_stat_type', models.CharField(blank=True, choices=[('shoutcast', 'Shoutcast'), ('wowza', 'Wowza')], max_length=20, null=True, verbose_name='Stat Type')),
            ],
        ),
        migrations.CreateModel(
            name='VoiceStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_stat_link', models.URLField(blank=True, null=True, verbose_name='Stat Link')),
                ('voice_stat_type', models.CharField(blank=True, choices=[('shoutcast', 'Shoutcast'), ('wowza', 'Wowza')], max_length=20, null=True, verbose_name='Stat Type')),
            ],
        ),
        migrations.CreateModel(
            name='VoiceContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_link', models.URLField(blank=True, null=True, verbose_name='لینک پخش زنده صوتی')),
                ('voice_stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Programs.voicestat', verbose_name='Voice Stat')),
            ],
        ),
        migrations.CreateModel(
            name='VideoContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_link', models.URLField(blank=True, null=True, verbose_name='لینک پخش زنده صوتی')),
                ('video_stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Programs.videostat', verbose_name='Video Stat')),
            ],
        ),
        migrations.CreateModel(
            name='StreamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_type', models.CharField(choices=[('audio', 'صوتی'), ('video', 'تصویری'), ('video_audio', 'صوتی و تصویری')], default='video_audio', max_length=15, verbose_name='نوع پخش زنده')),
                ('video_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Programs.videocontent', verbose_name='تصویری')),
                ('voice_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Programs.voicecontent', verbose_name='صوتی')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=70, unique=True, verbose_name='slug')),
                ('start_time', models.TimeField(verbose_name='زمان شروع')),
                ('end_time', models.TimeField(verbose_name='زمان پایان')),
                ('logo_link', models.URLField(default='https://lesansedgh.ir', verbose_name='لینک لوگو')),
                ('logo', models.ImageField(default='Programs/images/default_logo.png', upload_to='Programs/images/%Y_%m_%d', verbose_name='عکس')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییر')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='created', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('date_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Programs.datetype', verbose_name='تاریخ')),
                ('last_modified_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='last_modified', to=settings.AUTH_USER_MODEL, verbose_name='آخرین تغییر دهنده')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Programs.streamtype', verbose_name='محتویات برنامه')),
            ],
        ),
    ]
