# Generated by Django 4.0.1 on 2022-01-17 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Programs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='program',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='program',
            name='day',
            field=models.CharField(choices=[('shanbe', 'شنبه'), ('shanbe_1', 'شبنه 1'), ('shanbe_2', 'شبنه 2'), ('shanbe_3', 'شبنه 3'), ('shanbe_4', 'شبنه 4'), ('shanbe_5', 'شبنه 5'), ('jome', 'جمعه')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='is_active',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='program',
            name='logo',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
