# Generated by Django 4.0.1 on 2022-01-17 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Programs', '0002_program_author_program_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='author',
        ),
    ]
