# Generated by Django 4.0.1 on 2022-01-22 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Programs', '0002_program_last_modified_by_alter_program_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='program',
            name='last_modified_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='last_modified', to=settings.AUTH_USER_MODEL),
        ),
    ]
