# Generated by Django 4.0.1 on 2022-01-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Programs', '0003_remove_program_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='date_type',
            field=models.CharField(choices=[('weekly', 'هفتگی'), ('date', 'تاریخ مشخص')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='program',
            name='date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='day',
            field=models.CharField(blank=True, choices=[('shanbe', 'شنبه'), ('shanbe_1', 'شبنه 1'), ('shanbe_2', 'شبنه 2'), ('shanbe_3', 'شبنه 3'), ('shanbe_4', 'شبنه 4'), ('shanbe_5', 'شبنه 5'), ('jome', 'جمعه')], editable=False, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='logo',
            field=models.ImageField(default='Programs/images/default_logo.png', upload_to='Programs/images/%Y_%m_%d'),
        ),
        migrations.AlterField(
            model_name='program',
            name='logo_link',
            field=models.URLField(default='https://lesansedgh.ir'),
        ),
        migrations.AlterField(
            model_name='program',
            name='stat_video_link',
            field=models.URLField(blank=True, default='', editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='stat_video_type',
            field=models.CharField(blank=True, choices=[('shoutcast', 'Shoutcast'), ('wowza', 'Wowza')], editable=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='stat_voice_link',
            field=models.URLField(blank=True, default='', editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='stat_voice_type',
            field=models.CharField(blank=True, choices=[('shoutcast', 'Shoutcast'), ('wowza', 'Wowza')], editable=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='stream',
            field=models.CharField(choices=[('video', 'تصویری'), ('audio', 'صوتی'), ('video_audio', 'صوتی و تصویری')], default='video', max_length=11),
        ),
        migrations.AlterField(
            model_name='program',
            name='video_link',
            field=models.URLField(blank=True, default='', editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='voice_link',
            field=models.URLField(blank=True, default='', editable=False, null=True),
        ),
    ]
