# Generated by Django 4.0.1 on 2022-01-17 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Programs', '0004_program_date_type_alter_program_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='date_type',
        ),
        migrations.AlterField(
            model_name='program',
            name='stream',
            field=models.CharField(choices=[('audio', 'صوتی'), ('video', 'تصویری'), ('video_audio', 'صوتی و تصویری')], default='video', max_length=11),
        ),
    ]
