# Generated by Django 4.0.1 on 2022-01-17 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Programs', '0005_remove_program_date_type_alter_program_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='day',
            field=models.CharField(blank=True, choices=[('shanbe', 'شنبه'), ('shanbe_1', 'شبنه 1'), ('shanbe_2', 'شبنه 2'), ('shanbe_3', 'شبنه 3'), ('shanbe_4', 'شبنه 4'), ('shanbe_5', 'شبنه 5'), ('jome', 'جمعه')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='program',
            name='stat_video_link',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='stat_video_type',
            field=models.CharField(blank=True, choices=[('shoutcast', 'Shoutcast'), ('wowza', 'Wowza')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='stat_voice_link',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='stat_voice_type',
            field=models.CharField(blank=True, choices=[('shoutcast', 'Shoutcast'), ('wowza', 'Wowza')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='video_link',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='voice_link',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
